### ISSUE TITLE
Exception in farmware-tools request error handling

### ISSUE THREAD

**Issue by avonwyss** [FarmBot-Labs/farmware-tools#1]
I have a farmware which tries to create a point. Unfortunately the request fails, but I cannot see why since the farmware-tools fail as well (running on Farmbot with OS 7.0.1):
```
Traceback (most recent call last): 
File "MLH-master/MLH/main.py", line 22, in <module> app.execute() 
File "/root/farmware/meteoswissweather/MLH-master/MLH/Weather.py", line 58, in execute self.put_point(point) 
File "/root/farmware/meteoswissweather/MLH-master/MLH/Farmbot.py", line 428, in put_point return get_factory(Point)(app.put('/api/points', point.id, point) if point.id is not None else app.post('/api/points', cast(Any, point))) 
File "/root/farmware/meteoswissweather/farmware_tools/app.py", line 90, in post return request('POST', endpoint, **kwargs) 
File "/root/farmware/meteoswissweather/farmware_tools/app.py", line 79, in request print(response.json()) 
File "usr/lib/python3.7/site-packages/requests/models.py", line 897, in json File "usr/lib/python3.7/json/__init__.py", line 348, in loads 
File "usr/lib/python3.7/json/decoder.py", line 337, in decode 
File "usr/lib/python3.7/json/decoder.py", line 355, in raw_decode json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Apparently the data returned by the call is not JSON (I think I may be using an invalid endpoint URL), but the tools [blindly try to interpret it as JSON](https://github.com/FarmBot-Labs/farmware-tools/blob/f12cd6bfc91b1dd3d8ef0cc0195eca88d7c0dcad/farmware_tools/app.py#L79).

**Comment by gabrielburnworth** [comment]
Since `/api/points` is a valid endpoint, it's likely that the data you provided in the request is not valid JSON. I've updated `farmware-tools` (v3.2.0) to let it try to return the Web App API error when JSON is not returned. In the future hopefully the API will be changed to return JSON instead.

**Comment by avonwyss** [comment]
@gabrielburnworth Note that I have used this code: `app.post('/api/points', cast(Any, point))`
It should be `app.post('points', cast(Any, point))` instead, since the `farmware-tools` are adding the `/api/` part already. That's why I write that my URL is wrong.
